### PR TITLE
Fixes the compile error for Dart 2

### PR DESCRIPTION
**Pull request by gazialankus**
**Edit:** Fixed it to work with Dart2. Please see the comment below. 

However, still not compatible with Dart 2. We now get an infinite loop with AngularDart on caught errors. It was searching for a field .error of undefined.

### CODE REVIEW

**Comment by gazialankus** [comment]
Ok now it works for me in Dart 2 and AngularDart 5. I'm not sure if there was a better way to check whether LoggingServiceOriginalConsoleMethods.error et al. exist, but this works. Finally I see my exception in sentry.io :')

**Comment by Keksinautin** [comment]
Hi @gazialankus, 
Thank you a lot for the merge request. Now I am looking at it.  
I am trying to figure out something for   
`final _levelNames = new Map.fromIterable(log.Level.LEVELS, key: (dynamic l) => l.name, value: (dynamic l) => l);`
but may be better than `dynamic`.   
I see you tried to use generic for `new Map` but it helps only partly unfortunately. I am going to ask my friends from the Dart team about what is the right way they see for such situations.

**Comment by Keksinautin** [comment]
@gazialankus Hi, I did changes for Dart 2 comartibility, but in a little bit different way (you can take a look if you are interested in https://github.com/wrike/logging_service/pull/9/files).  
Now I have released v3.2.2 with these fixes, can you please try to use it and answer is it ok for you or not?

**Comment by gazialankus** [comment]
I put 3.2.2 to my pubspec.yaml and it worked just fine for me. `fromIterables` is definitely a better choice. Thank you!

**Pull request closed without merging**
